@MyWebAPI_HostAddress = http://localhost:5032

### Get All Attendance
GET {{MyWebAPI_HostAddress}}/api/attendance
Accept: application/json

### Get Attendance by ID
GET {{MyWebAPI_HostAddress}}/api/attendance/1
Accept: application/json

### Create Attendance
POST {{MyWebAPI_HostAddress}}/api/attendance
Content-Type: application/json

{
  "name": "Moiz Ahmed",
  "emailId": "moeezinbox@gmail.com",
  "mobileNumber": "9172499704",
  "isDeleted": false,
  "createdBy": "System",
  "createdOn": "2025-07-09T12:41:00.000Z"
}

###
PUT {{MyWebAPI_HostAddress}}/api/attendance/1
Content-Type: application/json

{
  "id": 1,
  "name": "Moiz Ahmed",
  "emailId": "moeezinbox@gmail.com",
  "mobileNumber": "9172499704",
  "isPresent": true,
  "createdOn": "2025-07-09T12:41:00.000Z"
}