@MyWebAPI_HostAddress = http://localhost:5032

### Get All Attendance
GET {{MyWebAPI_HostAddress}}/api/attendance
Accept: application/json

### Get Attendance by ID
GET {{MyWebAPI_HostAddress}}/api/attendance/1
Accept: application/json

### Create Attendance 1
POST {{MyWebAPI_HostAddress}}/api/attendance
Content-Type: application/json

{
  "name": "Tauseef Akhtar",
  "emailId": "tauseef.4158@gmail.com",
  "mobileNumber": "8380824158",
  "ipAddress": "203.194.107.110",
  "isDeleted": false,
  "createdBy": "System",
  "createdOn": "2025-07-23T12:25:43.000Z"
}

### Create Attendance 2
POST {{MyWebAPI_HostAddress}}/api/attendance
Content-Type: application/json

{
  "name": "Mohmmad Shoeb",
  "emailId": "shoebrayeen8697@gmail.com",
  "mobileNumber": "9579702736",
  "ipAddress": "203.194.107.110",
  "isDeleted": false,
  "createdBy": "System",
  "createdOn": "2025-07-23T12:25:43.000Z"
}

### Update Attendance
PUT {{MyWebAPI_HostAddress}}/api/attendance/1
Content-Type: application/json

{
  "id": 1,
  "name": "Moiz Ahmed",
  "emailId": "moeezinbox@gmail.com",
  "mobileNumber": "9172499704",
  "ipAddress": "192.168.0.1",
  "isPresent": true,
  "createdOn": "2025-07-09T12:41:00.000Z"
}

### Get Attendance Records by Filters
GET {{MyWebAPI_HostAddress}}/api/attendance/filters
Accept: application/json

{
  "name": "Moiz Ahmed",
  "fromDate": "2025-07-09T12:41:00.000Z",
  "toDate": "2025-07-09T12:41:00.000Z"
}

### Search Attendance
GET {{MyWebAPI_HostAddress}}/api/attendance/search?name=Moiz&fromdate=2025-07-01T12:41:00.000Z&todate=2025-07-31T12:41:00.000Z
Accept: application/json

### Edit Attendance
POST {{MyWebAPI_HostAddress}}/api/attendance/edit
Content-Type: application/json

{
  "id": 1,
  "name": "Moiz Ahmed",
  "emailId": "moeezinbox@gmail.com",
  "mobileNumber": "9172499704",
  "ipAddress": "192.168.0.1",
  "isPresent": true,
  "createdOn": "2025-07-09T12:41:00.000Z"
}