@MyWebAPI_HostAddress = http://localhost:5032

###
POST {{MyWebAPI_HostAddress}}/api/slack/task-update
Content-Type: application/json

###
POST {{MyWebAPI_HostAddress}}/auth/start
Content-Type: application/json
